server:
  global:
    scrape_interval: 15s
    evaluation_interval: 15s
  
  persistentVolume:
    size: 10Gi
  
  # Enable Prometheus service monitors
  serviceMonitors:
    enabled: true
    
  # Configure alerting rules
  alerting:
    alertmanagers:
      - static_configs:
          - targets:
            - alertmanager.monitoring.svc:9093

# Enable Prometheus rules for alerting
serverFiles:
  alerting_rules.yml:
    groups:
      - name: arcade-game-alerts
        rules:
          - alert: HighCPUUsage
            expr: sum(rate(container_cpu_usage_seconds_total{pod=~"arcade-game.*"}[5m])) by (pod) > 0.8
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High CPU usage on {{ $labels.pod }}"
              description: "{{ $labels.pod }} has high CPU usage (> 80%) for more than 5 minutes."
          
          - alert: HighMemoryUsage
            expr: sum(container_memory_usage_bytes{pod=~"arcade-game.*"}) by (pod) / sum(container_spec_memory_limit_bytes{pod=~"arcade-game.*"}) by (pod) > 0.8
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High memory usage on {{ $labels.pod }}"
              description: "{{ $labels.pod }} has high memory usage (> 80%) for more than 5 minutes."