apiVersion: v1
kind: Service
metadata:
  name: {{ include "arcade-game.fullname" . }}
  labels:
    {{- include "arcade-game.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.service.metrics.enabled }}
    - port: {{ .Values.service.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: {{ .Values.service.metrics.name }}
    {{- end }}
  selector:
    {{- include "arcade-game.selectorLabels" . | nindent 4 }}