elasticsearchHosts: "http://elasticsearch-master:9200"

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

service:
  type: ClusterIP

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: kibana.arcade-game.example.com
      paths:
        - path: /
          pathType: Prefix

extraEnvs:
  - name: ELASTICSEARCH_USERNAME
    value: elastic
  - name: ELASTICSEARCH_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elasticsearch-credentials
        key: password

dashboardImport:
  enabled: true
  timeout: 60
  dashboards:
    - name: arcade-game-overview
      configmap: kibana-dashboard-arcade-game