# Production environment values
replicaCount: 3

image:
  tag: release
  pullPolicy: Always

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: arcade-game.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: arcade-game-tls
      hosts:
        - arcade-game.example.com

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

env:
  - name: ENV
    value: "production"
  - name: LOG_LEVEL
    value: "warn"

# Production-specific labels
labels:
  environment: prod

# Enable ServiceMonitor for production environment
serviceMonitor:
  enabled: true
  interval: 10s  # More frequent scraping in production