name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install

    - name: Lint The code
      run: node node_modules/eslint/bin/eslint.js src/**/*.js
       
    - name: Build application
      run: npm run build

    - name: Run tests
      run: node node_modules/cross-env/src/bin/cross-env.js NODE_OPTIONS=--experimental-vm-modules node node_modules/jest/bin/jest.js

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        args: >
          -Dsonar.organization=sonbarse17
          -Dsonar.projectKey=sonbarse17_arcade-game-web
          -Dsonar.sources=. 
          -Dsonar.host.url=https://sonarcloud.io 
          -Dsonar.branch.name=${{ github.ref_name }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN_GITHUB }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/html5-arcade-game:latest,${{ secrets.DOCKER_USERNAME }}/html5-arcade-game:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max